spring.application.name=order-api

# Aws connection
aws.region=us-east-2
aws.sqs.orderCreatedQueueUrl=https://sqs.us-east-2.amazonaws.com/072518589151/order-created-queue
aws.dynamodb.ordersTable=SarapSeoul-Orders
